name: tma_data_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - blosc
  - brotli
  - brotlipy
  - brunsli
  - bwidget
  - bzip2
  - ca-certificates
  - cairo
  - cartopy
  - certifi
  - cffi
  - cftime
  - chardet
  - charls
  - cloudpickle
  - cryptography
  - curl
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - fontconfig
  - freeglut
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - geos
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - glib
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - jbig2dec
  - jpeg
  - jxrlib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libbezier
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv
  - liblapack
  - libnetcdf
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - libzopfli
  - lz4-c
  - make
  - matplotlib
  - matplotlib-base
  - ncurses
  - netcdf4
  - networkx
  - numpy
  - olefile
  - openjpeg
  - openssl
  - owslib
  - pandas
  - pango
  - patsy
  - pcre
  - pcre2
  - pip
  - pixman
  - poppler
  - poppler-data
  - proj
  - pthread-stubs
  - pycparser
  - pyepsg
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywavelets
  - pyyaml
  - r
  - r-base
  - r-boot
  - r-class
  - r-cluster
  - r-codetools
  - r-dplyr
  - r-foreign
  - r-kernsmooth
  - r-lattice
  - r-mass
  - r-matrix
  - r-mgcv
  - r-nlme
  - r-nnet
  - r-pdftools
  - r-purrr
  - r-recommended
  - r-rpart
  - r-spatial
  - r-stringr
  - r-survival
  - readline
  - requests
  - scikit-image
  - scipy
  - sed
  - setuptools
  - shapely
  - six
  - snappy
  - sqlite
  - statsmodels
  - tifffile
  - tk
  - tktable
  - toolz
  - tornado
  - urllib3
  - wheel
  - xarray
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zfp
  - zlib
  - zstd
  - pip:
    - bezier
